### ISSUE TITLE
MQTT service registration

### ISSUE THREAD

**Issue by tonobo** [victronenergy/dbus-flashmq#2]
Moin, at the moment there are some community projects available for feeding in data to venus os for 3rd-party devices like, pv-inverters, batteries or grid data.

* https://github.com/mr-manuel/venus-os_dbus-mqtt-grid
* https://github.com/mr-manuel/venus-os_dbus-mqtt-pv
* https://github.com/mr-manuel/venus-os_dbus-mqtt-battery

From my perspective this isn't really needed at some point in case the mqtt dbus driver were able to handle service registrations as well.
Are there some reasons why this hasn't been implemented so far?

**Comment by mpvader** [comment]
From a technical point of view: yes would be nice.

But its not urgent in our priority lists, since this doesn't benefit any Victron products / doesn't solve something that is not already solved in another way.

A PR would be welcome, though I have to warn in advance that I can't tell now if we want to add such extension to our standard code.
